### ISSUE TITLE
attributes missing from published crate?

### ISSUE THREAD

**Issue by gilescope** [SchrodingerZhu/tabbycat#1]
Couldn't find attributes in the latest published crate (use tabbycat::attributes::*;) - maybe time to republish?

The rest seems to work well though :-)

**Comment by gilescope** [comment]
Ah they're behind a feature (maybe call that out in the readme.md?)

**Comment by gilescope** [comment]
Ah you have already - sorry I just failed to read that bit.

**Comment by SchrodingerZhu** [comment]
never mind. happy to see the problem solved. :P
