### ISSUE TITLE
Pretty print function

### ISSUE THREAD

**Issue by vanillajonathan** [SchrodingerZhu/tabbycat#2]
It would be good with a pretty print function.

So instead of:
```dot
digraph G{A[color=red;];B->C[arrowhead=diamond;]};
```

It prints:
```dot
digraph G {
    A [color=red]
    B -> C [arrowhead=diamond]
}
```

**Comment by SchrodingerZhu** [comment]
Good idea. I will look into it.

**Comment by SchrodingerZhu** [comment]
sorry for the long delay. I am currently still in a school project. I promise adding this feature later. Anyone would like to contribute is also welcomed!

**Comment by SchrodingerZhu** [comment]
done
