### ISSUE TITLE
Publish and update

### ISSUE THREAD

**Issue by SchrodingerZhu** [SchrodingerZhu/tabbycat#6]
Follow up the recent updates.

**Comment by MingweiSamuel** [comment]
Any updates on this?

**Comment by ice1000** [comment]
@SchrodingerZhu it will be good to leave a comment before closing.

**Comment by SchrodingerZhu** [comment]
@ice1000 Thanks for the reminder. This was closed as 0.1.3 was published.

**Comment by ice1000** [comment]
> @ice1000 Thanks for the reminder. This was closed as 0.1.3 was published.

It would be good to have a badge in readme

**Comment by SchrodingerZhu** [comment]
> > @ice1000 Thanks for the reminder. This was closed as 0.1.3 was published.
> 
> It would be good to have a badge in readme

Yeah. I guess so.
