### ISSUE TITLE
[Question]: Is there something like an Owned Graph?

### ISSUE THREAD

**Issue by saona-raimundo** [SchrodingerZhu/tabbycat#7]
Thank you very much for the crate! I just started using it and wanted to ask for something.

# Request

An owned version of tabbycat::Graph.

# Details

I have a data structure and want to generate a `tabbycat::Graph` to represent it. 

The labels, ids, and attributes will be created during the representation, so they are not a reference to anything that my data structure has (I have fields that implement `Display`, but I do not want to store their representation beforehand). Therefore, it would be better to pass the owned data to `tabbycat`, but I can't.

**Comment by joshburkart** [comment]
+1 to this, it seems like by far the most common use case, and I don't see a way for `tabbycat` as currently designed to handle it. This seems to have been designed with premature memory optimization -- is it really likely that an application creating (not even rendering) dot graphs is going to be memory limited?

**Comment by joshburkart** [comment]
@SchrodingerZhu Would you accept a PR changing everything to be owned?

**Comment by SchrodingerZhu** [comment]
Hi.

I see the conversations here and I am seeking for maintainers for this project (or a new owner if anyone is interested). I am happy to accept PRs. Sorry for my slow responses. I am also sorry that currently I still cannot attach a high priority for this project. Hopefully I will sort everything out in several weeks.

As for the ownership issue, I agree with the idea that purely borrowed strs are indeed too restrictive for the usage and owned values should be a better choice. I would like to do a version bump after the PR. The maintenance is long overdue.

Feel free to make any suggestions.

Enjoy.

Sent from ProtonMail mobile

**Comment by joshburkart** [comment]
Great thank you @SchrodingerZhu; I'm excited to help out. Could you please give me permission to push branches other than master, so I can make PRs for you to review?

**Comment by ice1000** [comment]
> Great thank you @SchrodingerZhu; I'm excited to help out. Could you please give me permission to push branches other than master, so I can make PRs for you to review?

Forks should also work. IIRC, private repos do not have such fine-grained access control.
